<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Errors io.js v2.3.4 Manual &amp; Documentation</title>
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic">
  <link rel="stylesheet" href="assets/style.css">
  <link rel="stylesheet" href="assets/sh.css">
  <link rel="canonical" href="https://iojs.org/api/errors.html">
</head>
<body class="alt apidoc" id="api-section-errors">
  <div id="content" class="clearfix">
    <div id="column2" class="interior">
      <div id="intro" class="interior">
        <a href="/" title="Go back to the home page">
          io.js (1)
        </a>
      </div>
      <ul>
<li><a class="nav-documentation" href="documentation.html">About these Docs</a></li>
<li><a class="nav-synopsis" href="synopsis.html">Synopsis</a></li>
<li><a class="nav-assert" href="assert.html">Assertion Testing</a></li>
<li><a class="nav-buffer" href="buffer.html">Buffer</a></li>
<li><a class="nav-addons" href="addons.html">C/C++ Addons</a></li>
<li><a class="nav-child_process" href="child_process.html">Child Processes</a></li>
<li><a class="nav-cluster" href="cluster.html">Cluster</a></li>
<li><a class="nav-console" href="console.html">Console</a></li>
<li><a class="nav-crypto" href="crypto.html">Crypto</a></li>
<li><a class="nav-debugger" href="debugger.html">Debugger</a></li>
<li><a class="nav-dns" href="dns.html">DNS</a></li>
<li><a class="nav-domain" href="domain.html">Domain</a></li>
<li><a class="nav-errors active" href="errors.html">Errors</a></li>
<li><a class="nav-events" href="events.html">Events</a></li>
<li><a class="nav-fs" href="fs.html">File System</a></li>
<li><a class="nav-globals" href="globals.html">Globals</a></li>
<li><a class="nav-http" href="http.html">HTTP</a></li>
<li><a class="nav-https" href="https.html">HTTPS</a></li>
<li><a class="nav-modules" href="modules.html">Modules</a></li>
<li><a class="nav-net" href="net.html">Net</a></li>
<li><a class="nav-os" href="os.html">OS</a></li>
<li><a class="nav-path" href="path.html">Path</a></li>
<li><a class="nav-process" href="process.html">Process</a></li>
<li><a class="nav-punycode" href="punycode.html">Punycode</a></li>
<li><a class="nav-querystring" href="querystring.html">Query Strings</a></li>
<li><a class="nav-readline" href="readline.html">Readline</a></li>
<li><a class="nav-repl" href="repl.html">REPL</a></li>
<li><a class="nav-smalloc" href="smalloc.html">Smalloc</a></li>
<li><a class="nav-stream" href="stream.html">Stream</a></li>
<li><a class="nav-string_decoder" href="string_decoder.html">String Decoder</a></li>
<li><a class="nav-timers" href="timers.html">Timers</a></li>
<li><a class="nav-tls" href="tls.html">TLS/SSL</a></li>
<li><a class="nav-tty" href="tty.html">TTY</a></li>
<li><a class="nav-dgram" href="dgram.html">UDP/Datagram</a></li>
<li><a class="nav-url" href="url.html">URL</a></li>
<li><a class="nav-util" href="util.html">Utilities</a></li>
<li><a class="nav-v8" href="v8.html">V8</a></li>
<li><a class="nav-vm" href="vm.html">VM</a></li>
<li><a class="nav-zlib" href="zlib.html">ZLIB</a></li>
</ul>

    </div>

    <div id="column1" data-id="errors" class="interior">
      <header>
        <h1>io.js v2.3.4 Documentation</h1>
        <div id="gtoc">
          <p>
            <a href="index.html" name="toc">Index</a> |
            <a href="all.html">View on single page</a> |
            <a href="errors.json">View as JSON</a>
          </p>
        </div>
        <hr>
      </header>

      <div id="toc">
        <h2>Table of Contents</h2>
        <ul>
<li><a href="#errors_errors">Errors</a><ul>
<li><a href="#errors_javascript_errors">JavaScript Errors</a><ul>
<li><a href="#errors_class_error">Class: Error</a><ul>
<li><a href="#errors_new_error_message">new Error(message)</a></li>
<li><a href="#errors_error_message">error.message</a></li>
<li><a href="#errors_error_stack">error.stack</a></li>
<li><a href="#errors_error_capturestacktrace_targetobject_constructoropt">Error.captureStackTrace(targetObject[, constructorOpt])</a></li>
<li><a href="#errors_error_stacktracelimit">Error.stackTraceLimit</a></li>
</ul>
</li>
<li><a href="#errors_class_rangeerror">Class: RangeError</a></li>
<li><a href="#errors_class_typeerror">Class: TypeError</a></li>
<li><a href="#errors_class_referenceerror">Class: ReferenceError</a></li>
<li><a href="#errors_class_syntaxerror">Class: SyntaxError</a></li>
<li><a href="#errors_exceptions_vs_errors">Exceptions vs. Errors</a></li>
</ul>
</li>
<li><a href="#errors_system_errors">System Errors</a><ul>
<li><a href="#errors_class_system_error">Class: System Error</a><ul>
<li><a href="#errors_error_syscall">error.syscall</a></li>
<li><a href="#errors_error_errno">error.errno</a></li>
<li><a href="#errors_error_code">error.code</a></li>
</ul>
</li>
<li><a href="#errors_common_system_errors">Common System Errors</a><ul>
<li><a href="#errors_eperm_operation_not_permitted">EPERM: Operation not permitted</a></li>
<li><a href="#errors_enoent_no_such_file_or_directory">ENOENT: No such file or directory</a></li>
<li><a href="#errors_eacces_permission_denied">EACCES: Permission denied</a></li>
<li><a href="#errors_eexist_file_exists">EEXIST: File exists</a></li>
<li><a href="#errors_enotdir_not_a_directory">ENOTDIR: Not a directory</a></li>
<li><a href="#errors_eisdir_is_a_directory">EISDIR: Is a directory</a></li>
<li><a href="#errors_emfile_too_many_open_files_in_system">EMFILE: Too many open files in system</a></li>
<li><a href="#errors_epipe_broken_pipe">EPIPE: Broken pipe</a></li>
<li><a href="#errors_eaddrinuse_address_already_in_use">EADDRINUSE: Address already in use</a></li>
<li><a href="#errors_econnreset_connection_reset_by_peer">ECONNRESET: Connection reset by peer</a></li>
<li><a href="#errors_econnrefused_connection_refused">ECONNREFUSED: Connection refused</a></li>
<li><a href="#errors_enotempty_directory_not_empty">ENOTEMPTY: Directory not empty</a></li>
<li><a href="#errors_etimedout_operation_timed_out">ETIMEDOUT: Operation timed out</a></li>
</ul>
</li>
</ul>
</li>
<li><a href="#errors_error_propagation_and_interception">Error Propagation and Interception</a><ul>
<li><a href="#errors_node_style_callbacks">Node style callbacks</a></li>
<li><a href="#errors_error_events">Error events</a></li>
</ul>
</li>
</ul>
</li>
</ul>

      </div>

      <div id="apicontent">
        <h1>Errors<span><a class="mark" href="#errors_errors" id="errors_errors">#</a></span></h1>
<!--type=misc-->

<p>Errors generated by io.js fall into two categories: JavaScript errors and system
errors. All errors inherit from or are instances of JavaScript&#39;s <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error">Error</a>
class and are guaranteed to provide <em>at least</em> the attributes available on that
class.

</p>
<p>When an operation is not permitted due to language-syntax or
language-runtime-level reasons, a <strong>JavaScript error</strong> is generated and thrown
as an <strong>exception</strong>. If an operation is not allowed due to system-level
restrictions, a <strong>system error</strong> is generated. Client code is then given the
opportunity to <strong>intercept</strong> this error based on how the API <strong>propagates</strong> it.

</p>
<p>The style of API called determines how generated errors are handed back, or
<strong>propagated</strong>, to client code, which in turn informs how the client may <strong>intercept</strong>
the error. Exceptions can be intercepted using the <code>try / catch</code> construct;
other propagation strategies are covered <a href="#errors_error_propagation_and_interception">below</a>.

</p>
<h2>JavaScript Errors<span><a class="mark" href="#errors_javascript_errors" id="errors_javascript_errors">#</a></span></h2>
<!--type=misc-->

<p>JavaScript errors typically denote that an API is being used incorrectly, or that
there is a problem with the program as written.

</p>
<h3>Class: Error<span><a class="mark" href="#errors_class_error" id="errors_class_error">#</a></span></h3>
<!--type=class-->

<p>A general error object. Unlike other error objects, <code>Error</code> instances do not
denote any specific circumstance of why the error occurred. Errors capture a
&quot;stack trace&quot; detailing the point in the program at which they were
instantiated, and may provide a description of the error.

</p>
<p><strong>Note</strong>: io.js will generate this class of error to encapsulate system
errors as well as plain JavaScript errors.

</p>
<h4>new Error(message)<span><a class="mark" href="#errors_new_error_message" id="errors_new_error_message">#</a></span></h4>
<p>Instantiates a new Error object and sets its <code>.message</code> property to the provided
message. Its <code>.stack</code> will represent the point in the program at which <code>new Error</code>
was called. Stack traces are subject to <a href="https://code.google.com/p/v8-wiki/wiki/JavaScriptStackTraceApi">V8&#39;s stack trace API</a>. 
Stack traces only extend to the beginning of synchronous code execution, <em>or</em> a number of frames given by
<code>Error.stackTraceLimit</code>, whichever is smaller.

</p>
<h4>error.message<span><a class="mark" href="#errors_error_message" id="errors_error_message">#</a></span></h4>
<p>A string of the value passed to <code>Error()</code> upon instantiation. The message will
also appear in the first line of the stack trace of the error. Changing this
property <em>may not</em> change the first line of the stack trace.

</p>
<h4>error.stack<span><a class="mark" href="#errors_error_stack" id="errors_error_stack">#</a></span></h4>
<p>A property that, when <strong>accessed</strong>, returns a string representing the point in the program
at which this error was instantiated. An example stacktrace follows:

</p>
<pre><code>Error: Things keep happening!
   at /home/gbusey/file.js:525:2
   at Frobnicator.refrobulate (/home/gbusey/business-logic.js:424:21)
   at Actor.&lt;anonymous&gt; (/home/gbusey/actors.js:400:8)
   at increaseSynergy (/home/gbusey/actors.js:701:6)</code></pre>
<p>The first line is formatted as <code>&lt;error class name&gt;: &lt;error message&gt;</code>, and it is followed
by a series of stack frames (each line beginning with &quot;at &quot;). Each frame describes
a call site in the program that lead to the error being generated. V8 attempts to
display a name for each function (by variable name, function name, or object 
method name), but occasionally it will not be able to find a suitable name. If
V8 cannot determine a name for the function, only location information will be
displayed for that frame. Otherwise, the determined function name will be displayed
with location information appended in parentheses. 

</p>
<p>Frames are <strong>only</strong> generated for JavaScript functions. If, for example, execution 
synchronously passes through a C++ addon function called <code>cheetahify</code>, which itself 
calls a JavaScript function, the frame representing the <code>cheetahify</code> call will <strong>not</strong> 
be present in stacktraces:

</p>
<pre><code class="javascript">var cheetahify = require(&#39;./native-binding.node&#39;);

function makeFaster() {
  // cheetahify *synchronously* calls speedy.
  cheetahify(function speedy() {
    throw new Error(&#39;oh no!&#39;);
  });
}

makeFaster(); // will throw:
// /home/gbusey/file.js:6
//     throw new Error(&#39;oh no!&#39;);
//           ^
// Error: oh no!
//     at speedy (/home/gbusey/file.js:6:11)
//     at makeFaster (/home/gbusey/file.js:5:3)
//     at Object.&lt;anonymous&gt; (/home/gbusey/file.js:10:1)
//     at Module._compile (module.js:456:26)
//     at Object.Module._extensions..js (module.js:474:10)
//     at Module.load (module.js:356:32)
//     at Function.Module._load (module.js:312:12)
//     at Function.Module.runMain (module.js:497:10)
//     at startup (node.js:119:16)
//     at node.js:906:3</code></pre>
<p>The location information will be one of: 

</p>
<ul>
<li><code>native</code>, if the frame represents a call internal to V8 (as in <code>[].forEach</code>).</li>
<li><code>plain-filename.js:line:column</code>, if the frame represents a call internal to io.js.</li>
<li><code>/absolute/path/to/file.js:line:column</code>, if the frame represents a call in a user program, or its dependencies.</li>
</ul>
<p>It is important to note that the string representing the stacktrace is only
generated on <strong>access</strong>: it is lazily generated. 

</p>
<p>The number of frames captured by the stack trace is bounded by the smaller of
<code>Error.stackTraceLimit</code> or the number of available frames on the current event
loop tick.

</p>
<p>System-level errors are generated as augmented Error instances, which are detailed
<a href="#errors_system_errors">below</a>.

</p>
<h4>Error.captureStackTrace(targetObject[, constructorOpt])<span><a class="mark" href="#errors_error_capturestacktrace_targetobject_constructoropt" id="errors_error_capturestacktrace_targetobject_constructoropt">#</a></span></h4>
<p>Creates a <code>.stack</code> property on <code>targetObject</code>, which when accessed returns
a string representing the location in the program at which <code>Error.captureStackTrace</code>
was called.

</p>
<pre><code class="javascript">var myObject = {};

Error.captureStackTrace(myObject);

myObject.stack  // similar to `new Error().stack`</code></pre>
<p>The first line of the trace, instead of being prefixed with <code>ErrorType:
message</code>, will be the result of <code>targetObject.toString()</code>.

</p>
<p><code>constructorOpt</code> optionally accepts a function. If given, all frames above
<code>constructorOpt</code>, including <code>constructorOpt</code>, will be omitted from the generated
stack trace. 

</p>
<p>This is useful for hiding implementation details of error generation from the
end user. A common way of using this parameter is to pass the current Error
constructor to it:

</p>
<pre><code class="javascript">
function MyError() {
  Error.captureStackTrace(this, MyError);
}

// without passing MyError to captureStackTrace, the MyError
// frame would should up in the .stack property. by passing
// the constructor, we omit that frame and all frames above it.
new MyError().stack</code></pre>
<h4>Error.stackTraceLimit<span><a class="mark" href="#errors_error_stacktracelimit" id="errors_error_stacktracelimit">#</a></span></h4>
<p>Property that determines the number of stack frames collected by a stack trace
(whether generated by <code>new Error().stack</code> or <code>Error.captureStackTrace(obj)</code>).

</p>
<p>The initial value is <code>10</code>. It may be set to any valid JavaScript number, which
will affect any stack trace captured <em>after</em> the value has been changed. If set
to a non-number value, stack traces will not capture any frames and will report
<code>undefined</code> on access.

</p>
<h3>Class: RangeError<span><a class="mark" href="#errors_class_rangeerror" id="errors_class_rangeerror">#</a></span></h3>
<p>A subclass of Error that indicates that a provided argument was not within the
set or range of acceptable values for a function; whether that be a numeric
range, or outside the set of options for a given function parameter. An example:

</p>
<pre><code class="javascript">require(&#39;net&#39;).connect(-1);  // throws RangeError, port should be &gt; 0 &amp;&amp; &lt; 65536</code></pre>
<p>io.js will generate and throw RangeError instances <em>immediately</em> -- they are a form
of argument validation. 

</p>
<h3>Class: TypeError<span><a class="mark" href="#errors_class_typeerror" id="errors_class_typeerror">#</a></span></h3>
<p>A subclass of Error that indicates that a provided argument is not an allowable
type. For example, passing a function to a parameter which expects a string would
be considered a TypeError.

</p>
<pre><code class="javascript">require(&#39;url&#39;).parse(function() { }); // throws TypeError, since it expected a string</code></pre>
<p>io.js will generate and throw TypeError instances <em>immediately</em> -- they are a form
of argument validation.

</p>
<h3>Class: ReferenceError<span><a class="mark" href="#errors_class_referenceerror" id="errors_class_referenceerror">#</a></span></h3>
<p>A subclass of Error that indicates that an attempt is being made to access a variable
that is not defined. Most commonly it indicates a typo, or an otherwise broken program.
While client code may generate and propagate these errors, in practice only V8 will do
so.

</p>
<pre><code class="javascript">doesNotExist; // throws ReferenceError, doesNotExist is not a variable in this program.</code></pre>
<p>ReferenceError instances will have an <code>.arguments</code> member that is an array containing
one element -- a string representing the variable that was not defined.

</p>
<pre><code class="javascript">try {
  doesNotExist;
} catch(err) {
  err.arguments[0] === &#39;doesNotExist&#39;;
}</code></pre>
<p>Unless the userland program is dynamically generating and running code,
ReferenceErrors should always be considered a bug in the program, or its
dependencies.

</p>
<h3>Class: SyntaxError<span><a class="mark" href="#errors_class_syntaxerror" id="errors_class_syntaxerror">#</a></span></h3>
<p>A subclass of Error that indicates that a program is not valid JavaScript.
These errors may only be generated and propagated as a result of code
evaluation. Code evaluation may happen as a result of <code>eval</code>, <code>Function</code>,
<code>require</code>, or <a href="vm.html">vm</a>. These errors are almost always indicative of a broken
program.

</p>
<pre><code class="javascript">try {
  require(&quot;vm&quot;).runInThisContext(&quot;binary ! isNotOk&quot;);
} catch(err) {
  // err will be a SyntaxError
}</code></pre>
<p>SyntaxErrors are unrecoverable from the context that created them – they may only be caught
by other contexts.

</p>
<h3>Exceptions vs. Errors<span><a class="mark" href="#errors_exceptions_vs_errors" id="errors_exceptions_vs_errors">#</a></span></h3>
<!--type=misc-->

<p>A JavaScript &quot;exception&quot; is a value that is thrown as a result of an invalid operation or
as the target of a <code>throw</code> statement. While it is not required that these values inherit from
<code>Error</code>, all exceptions thrown by io.js or the JavaScript runtime <em>will</em> be instances of Error.

</p>
<p>Some exceptions are <em>unrecoverable</em> at the JavaScript layer. These exceptions will always bring 
down the process. These are usually failed <code>assert()</code> checks or <code>abort()</code> calls in the C++ layer.

</p>
<h2>System Errors<span><a class="mark" href="#errors_system_errors" id="errors_system_errors">#</a></span></h2>
<p>System errors are generated in response to a program&#39;s runtime environment.
Ideally, they represent operational errors that the program needs to be able to
react to. They are generated at the syscall level: an exhaustive list of error
codes and their meanings is available by running <code>man 2 intro</code> or <code>man 3 errno</code>
on most Unices; or <a href="http://man7.org/linux/man-pages/man3/errno.3.html">online</a>.

</p>
<p>In io.js, system errors are represented as augmented Error objects -- not full
subclasses, but instead an error instance with added members.

</p>
<h3>Class: System Error<span><a class="mark" href="#errors_class_system_error" id="errors_class_system_error">#</a></span></h3>
<h4>error.syscall<span><a class="mark" href="#errors_error_syscall" id="errors_error_syscall">#</a></span></h4>
<p>A string representing the <a href="http://man7.org/linux/man-pages/man2/syscall.2.html">syscall</a> that failed.

</p>
<h4>error.errno<span><a class="mark" href="#errors_error_errno" id="errors_error_errno">#</a></span></h4>
<h4>error.code<span><a class="mark" href="#errors_error_code" id="errors_error_code">#</a></span></h4>
<p>A string representing the error code, which is always <code>E</code> followed by capital
letters, and may be referenced in <code>man 2 intro</code>.

</p>
<h3>Common System Errors<span><a class="mark" href="#errors_common_system_errors" id="errors_common_system_errors">#</a></span></h3>
<p>This list is <strong>not exhaustive</strong>, but enumerates many of the common system errors when
writing a io.js program. An exhaustive list may be found <a href="http://man7.org/linux/man-pages/man3/errno.3.html">here</a>.

</p>
<h4>EPERM: Operation not permitted<span><a class="mark" href="#errors_eperm_operation_not_permitted" id="errors_eperm_operation_not_permitted">#</a></span></h4>
<p>An attempt was made to perform an operation that requires appropriate
privileges.

</p>
<h4>ENOENT: No such file or directory<span><a class="mark" href="#errors_enoent_no_such_file_or_directory" id="errors_enoent_no_such_file_or_directory">#</a></span></h4>
<p>Commonly raised by <a href="fs.html">fs</a> operations; a component of the specified pathname
does not exist -- no entity (file or directory) could be found by the given path.

</p>
<h4>EACCES: Permission denied<span><a class="mark" href="#errors_eacces_permission_denied" id="errors_eacces_permission_denied">#</a></span></h4>
<p>An attempt was made to access a file in a way forbidden by its file access 
permissions.

</p>
<h4>EEXIST: File exists<span><a class="mark" href="#errors_eexist_file_exists" id="errors_eexist_file_exists">#</a></span></h4>
<p>An existing file was the target of an operation that required that the target
not exist.

</p>
<h4>ENOTDIR: Not a directory<span><a class="mark" href="#errors_enotdir_not_a_directory" id="errors_enotdir_not_a_directory">#</a></span></h4>
<p>A component of the given pathname existed, but was not a directory as expected.
Commonly raised by <a href="fs.html#fs_fs_readdir_path_callback">fs.readdir</a>. 

</p>
<h4>EISDIR: Is a directory<span><a class="mark" href="#errors_eisdir_is_a_directory" id="errors_eisdir_is_a_directory">#</a></span></h4>
<p>An operation expected a file, but the given pathname was a directory.

</p>
<h4>EMFILE: Too many open files in system<span><a class="mark" href="#errors_emfile_too_many_open_files_in_system" id="errors_emfile_too_many_open_files_in_system">#</a></span></h4>
<p>Maxiumum number of <a href="http://en.wikipedia.org/wiki/File_descriptor">file descriptors</a> allowable on the system has
been reached, and requests for another descriptor cannot be fulfilled until
at least one has been closed.

</p>
<p>Commonly encountered when opening many files at once in parallel, especially
on systems (in particular, OS X) where there is a low file descriptor limit
for processes. To remedy a low limit, run <code>ulimit -n 2048</code> in the same shell
that will run the io.js process.

</p>
<h4>EPIPE: Broken pipe<span><a class="mark" href="#errors_epipe_broken_pipe" id="errors_epipe_broken_pipe">#</a></span></h4>
<p>A write on a pipe, socket, or FIFO for which there is no process to read the
data. Commonly encountered at the <a href="net.html">net</a> and <a href="http.html">http</a> layers, indicative that
the remote side of the stream being written to has been closed.

</p>
<h4>EADDRINUSE: Address already in use<span><a class="mark" href="#errors_eaddrinuse_address_already_in_use" id="errors_eaddrinuse_address_already_in_use">#</a></span></h4>
<p>An attempt to bind a server (<a href="net.html">net</a>, <a href="http.html">http</a>, or <a href="https.html">https</a>) to a local
address failed due to another server on the local system already occupying
that address.

</p>
<h4>ECONNRESET: Connection reset by peer<span><a class="mark" href="#errors_econnreset_connection_reset_by_peer" id="errors_econnreset_connection_reset_by_peer">#</a></span></h4>
<p>A connection was forcibly closed by a peer. This normally results
from a loss of the connection on the remote socket due to a timeout
or reboot. Commonly encountered via the <a href="http.html">http</a> and <a href="net.html">net</a> modules.

</p>
<h4>ECONNREFUSED: Connection refused<span><a class="mark" href="#errors_econnrefused_connection_refused" id="errors_econnrefused_connection_refused">#</a></span></h4>
<p>No connection could be made because the target machine actively refused
it. This usually results from trying to connect to a service that is inactive
on the foreign host.

</p>
<h4>ENOTEMPTY: Directory not empty<span><a class="mark" href="#errors_enotempty_directory_not_empty" id="errors_enotempty_directory_not_empty">#</a></span></h4>
<p>A directory with entries was the target of an operation that requires
an empty directory -- usually <a href="fs.html#fs_fs_unlink_path_callback">fs.unlink</a>.

</p>
<h4>ETIMEDOUT: Operation timed out<span><a class="mark" href="#errors_etimedout_operation_timed_out" id="errors_etimedout_operation_timed_out">#</a></span></h4>
<p>A connect or send request failed because the connected party did not properly
respond after a period of time. Usually encountered by <a href="http.html">http</a> or <a href="net.html">net</a> --
often a sign that a connected socket was not <code>.end()</code>&#39;d appropriately.

</p>
<h2>Error Propagation and Interception<span><a class="mark" href="#errors_error_propagation_and_interception" id="errors_error_propagation_and_interception">#</a></span></h2>
<!--type=misc-->

<p>All io.js APIs will treat invalid arguments as exceptional -- that is, if passed
invalid arguments, they will <em>immediately</em> generate and throw the error as an
exception, even if they are an otherwise asynchronous API.

</p>
<p>Synchronous APIs (like
<a href="fs.html#fs_fs_readfilesync_filename_options">fs.readFileSync</a>) will throw the
error. The act of <em>throwing</em> a value (in this case, the error) turns the value
into an <strong>exception</strong>.  Exceptions may be caught using the <code>try { } catch(err)
{ }</code> construct. 

</p>
<p>Asynchronous APIs have <strong>two</strong> mechanisms for error propagation; one mechanism
for APIs that represent a single operation, and one for APIs that represent
multiple operations over time.

</p>
<h3>Node style callbacks<span><a class="mark" href="#errors_node_style_callbacks" id="errors_node_style_callbacks">#</a></span></h3>
<!--type=misc-->

<p>Single operation APIs take &quot;node style callbacks&quot; -- a
function provided to the API as an argument. The node style callback takes
at least <strong>one</strong> argument -- <code>error</code> -- that will either be <code>null</code> (if no error
was encountered) or an <code>Error</code> instance.  For instance:

</p>
<pre><code class="javascript">var fs = require(&#39;fs&#39;);

fs.readFile(&#39;/some/file/that/does-not-exist&#39;, function nodeStyleCallback(err, data) {
  console.log(err)  // Error: ENOENT
  console.log(data) // undefined / null
});

fs.readFile(&#39;/some/file/that/does-exist&#39;, function(err, data) {
  console.log(err)  // null
  console.log(data) // &lt;Buffer: ba dd ca fe&gt;
})</code></pre>
<p>Note that <code>try { } catch(err) { }</code> <strong>cannot</strong> intercept errors generated by
asynchronous APIs. A common mistake for beginners is to try to use <code>throw</code>
inside their node style callback:

</p>
<pre><code class="javascript">// THIS WILL NOT WORK:
var fs = require(&#39;fs&#39;);

try {
  fs.readFile(&#39;/some/file/that/does-not-exist&#39;, function(err, data) {
    // mistaken assumption: throwing here...
    if (err) {
      throw err;
    }
  });
} catch(err) {
  // ... will be caught here -- this is incorrect!
  console.log(err); // Error: ENOENT
}</code></pre>
<p>This will not work! By the time the node style callback has been called, the
surrounding code (including the <code>try { } catch(err) { }</code> will have already
exited. Throwing an error inside a node style callback <strong>will crash the process</strong> in most cases.
If <a href="domain.html">domains</a> are enabled, they may intercept the thrown error; similarly, if a
handler has been added to <code>process.on(&#39;uncaughtException&#39;)</code>, it will intercept
the error.

</p>
<h3>Error events<span><a class="mark" href="#errors_error_events" id="errors_error_events">#</a></span></h3>
<!--type=misc-->

<p>The other mechanism for providing errors is the &quot;error&quot; event. This is
typically used by <a href="stream.html">stream-based</a> and <a href="events.html#events_class_events_eventemitter">event emitter-based</a> APIs, which
themselves represent a series of asynchronous operations over time (versus a
single operation that may pass or fail). If no &quot;error&quot; event handler is
attached to the source of the error, the error will be thrown. At this point,
it will crash the process as an unhandled exception unless <a href="domain.html">domains</a> are
employed appropriately or <a href="process.html#process_event_uncaughtexception">process.on(&#39;uncaughtException&#39;)</a> has a handler.

</p>
<pre><code class="javascript">var net = require(&#39;net&#39;);

var connection = net.connect(&#39;localhost&#39;);

// adding an &quot;error&quot; event handler to a stream:
connection.on(&#39;error&#39;, function(err) {
  // if the connection is reset by the server, or if it can&#39;t
  // connect at all, or on any sort of error encountered by
  // the connection, the error will be sent here.
  console.error(err);
});

connection.pipe(process.stdout);</code></pre>
<p>The &quot;throw when no error handlers are attached behavior&quot; is not limited to APIs
provided by io.js -- even user created event emitters and streams will throw
errors when no error handlers are attached. An example:

</p>
<pre><code class="javascript">var events = require(&#39;events&#39;);

var ee = new events.EventEmitter;

setImmediate(function() {
  // this will crash the process because no &quot;error&quot; event
  // handler has been added.
  ee.emit(&#39;error&#39;, new Error(&#39;This will crash&#39;));
});</code></pre>
<p>As with node style callbacks, errors generated this way <em>cannot</em> be intercepted
by <code>try { } catch(err) { }</code> -- they happen <em>after</em> the calling code has already
exited.
</p>

      </div>
    </div>
  </div>
  <div id="footer">
  </div>

  <script src="assets/sh_main.js"></script>
  <script src="assets/sh_javascript.min.js"></script>
  <script>highlight(undefined, undefined, 'pre');</script>
</body>
</html>

